# Generated by Django 5.0.3 on 2024-03-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto_precio_producto_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
